title: Practice Directions
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
elastic_search:
  index: pd
  doctype: bare
environment: DEV
server_LOCAL: http://127.0.0.1:3000
server_DEV: https://opendoc.sg
